name: Integration-Continue
on:
  pull_request:
  push:
jobs:
  Integration-Continue:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 8

      - name: Build project
        run: ./gradlew clean compileJava

      - name: Test Project
        run: ./gradlew clean test --info
